// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgPdc7leZ7IYDkIay7PNC-SyDA7eU82eY',
    appId: '1:903387295113:web:54c4a845df21c2e4b48558',
    messagingSenderId: '903387295113',
    projectId: 'blood-816b4',
    authDomain: 'blood-816b4.firebaseapp.com',
    storageBucket: 'blood-816b4.firebasestorage.app',
    measurementId: 'G-4P1754140K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5D-ih1ZhHCEPxIKPoeRUT-tYWvjQDqM',
    appId: '1:903387295113:android:8e45abad902fedb4b48558',
    messagingSenderId: '903387295113',
    projectId: 'blood-816b4',
    storageBucket: 'blood-816b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5a1iP_9fpQKf0dk_bpc4TLRZE20w4QiI',
    appId: '1:903387295113:ios:001da6a6da708a02b48558',
    messagingSenderId: '903387295113',
    projectId: 'blood-816b4',
    storageBucket: 'blood-816b4.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5a1iP_9fpQKf0dk_bpc4TLRZE20w4QiI',
    appId: '1:903387295113:ios:001da6a6da708a02b48558',
    messagingSenderId: '903387295113',
    projectId: 'blood-816b4',
    storageBucket: 'blood-816b4.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgPdc7leZ7IYDkIay7PNC-SyDA7eU82eY',
    appId: '1:903387295113:web:e7a25602634f9d9db48558',
    messagingSenderId: '903387295113',
    projectId: 'blood-816b4',
    authDomain: 'blood-816b4.firebaseapp.com',
    storageBucket: 'blood-816b4.firebasestorage.app',
    measurementId: 'G-PXL2LXG2MW',
  );
}
